<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-12345678910111213141516171819202122_51e29d</name>
   <tag></tag>
   <elementGuidId>1af55d1d-d96c-439d-aed6-c279527bbbae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='days']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#days</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>833d4403-3554-474f-9705-09e94cbe299e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>days</value>
      <webElementGuid>e5a84ed5-090f-4bbb-b39b-065d78c6a32f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>days</value>
      <webElementGuid>eedc3d01-51a1-45a6-aca1-36b4f0eb0a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>631cd2e7-6a02-4e04-ba10-75f963d617fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
							-
															1  
															2  
															3  
															4  
															5  
															6  
															7  
															8  
															9  
															10  
															11  
															12  
															13  
															14  
															15  
															16  
															17  
															18  
															19  
															20  
															21  
															22  
															23  
															24  
															25  
															26  
															27  
															28  
															29  
															30  
															31  
													</value>
      <webElementGuid>5bd82e5a-ed09-4b21-81ea-11e14b45fbe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;days&quot;)</value>
      <webElementGuid>394fdbee-f9ce-4485-b5bb-e07d4f673ccc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='days']</value>
      <webElementGuid>5e57e156-a061-4c2a-a5e0-74678e1fd1d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uniform-days']/select</value>
      <webElementGuid>34199f8c-7580-4c95-999d-65e8033c8680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::select[1]</value>
      <webElementGuid>14c50295-0e2b-4358-8030-9b7c7c582339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of Birth'])[1]/following::select[1]</value>
      <webElementGuid>e73e375b-2f4c-47c0-90a0-168bd84b4755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[3]/preceding::select[1]</value>
      <webElementGuid>f608355b-678f-4fb3-bfdd-b44aeb8d020f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[5]/preceding::select[2]</value>
      <webElementGuid>63fd745e-db6b-4227-afde-77c66230f8e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>abd70c2c-d90b-4010-aada-1cf55e9a06eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'days' and @name = 'days' and (text() = '
							-
															1  
															2  
															3  
															4  
															5  
															6  
															7  
															8  
															9  
															10  
															11  
															12  
															13  
															14  
															15  
															16  
															17  
															18  
															19  
															20  
															21  
															22  
															23  
															24  
															25  
															26  
															27  
															28  
															29  
															30  
															31  
													' or . = '
							-
															1  
															2  
															3  
															4  
															5  
															6  
															7  
															8  
															9  
															10  
															11  
															12  
															13  
															14  
															15  
															16  
															17  
															18  
															19  
															20  
															21  
															22  
															23  
															24  
															25  
															26  
															27  
															28  
															29  
															30  
															31  
													')]</value>
      <webElementGuid>fd0bc4d1-3c04-4518-8f15-1a8d3bb4be06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
